### PR TITLE
Nav 183 make viewer app responsive

### PR DESCRIPTION
**Pull request by clukas1**
Hacky workarounds, but should do the job for this project.

### CODE REVIEW

**Comment by munterfi** [comment]
Thanks @clukas1, nice work!

Unfortunately, sometimes the map doesn't display, such as when routing from Wädenswil to Gurten Kulm:

image

And the map:
image

Other routes work fine. Maybe it has something to do with connections that consist of many legs?

**Comment by munterfi** [comment]
Another example:

image

**Comment by clukas1** [comment]
> Thanks @clukas1, nice work!
> 
> Unfortunately, sometimes the map doesn't display, such as when routing from Wädenswil to Gurten Kulm:
> 
> Other routes work fine. Maybe it has something to do with connections that consist of many legs?

Thanks for finding this issue, this was due to a syntax error caused by my 6' Walk strings, which resulted in bindPopup('6' Walk'); --> syntax error.

fixed in 4279c84

**Comment by munterfi** [comment]
Thanks @clukas1!

Now it works for most cases, but there are still some cases where the map fails to load:

- Connection:
image

- Map:
image

**Comment by clukas1** [comment]
@munterfi thanks for the comprehensive testing.

Looks like it was the same issue ' (single quotes) in text. This time french name `Flon, pl. de l'Europe`. I've now added an escape string method to hopefully prevent all cases now. (55e526c)

image

**Comment by munterfi** [comment]
Thanks @clukas1, looks good to merge.

**Review by munterfi — APPROVED** [review]

**Pull request merged**
